services:
  - type: web
    name: SmartMacros
    runtime: ruby # this app is written in ruby
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "./bin/render-build.sh" # we already created these two files for you
    startCommand: "./bin/render-start.sh"
    envVars: # this section sets some ENV variables needed by Render for deployment
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://kpm136:xau_r7ZrvdeIPuTS21cvwCeDqx9i5NA0V3nL7@us-east-1.sql.xata.sh/SmartMacrosDB:main?sslmode=require
      - key: WEB_CONCURRENCY
        value: 2
    postDeployCommand: 'bundle exec rails db:migrate && bundle exec rails db:seed'

